### ISSUE TITLE
Send conversation

### ISSUE THREAD

**Issue by RasaCosmin** [IdoTene/Xamarin-Freshdesk-Android#1]
Hi Ido, 
I integrate your mobihelp_sdk_android_v1.3.1.dll in my xamarin android app, but when I try to send a text from conversation activity, I get the following exception : 
android.content.res.Resources$NotFoundException: String resource ID #0x0
[MOBIHELP]  at android.content.res.Resources.getText(Resources.java:245)
[MOBIHELP]  at android.content.res.Resources.getString(Resources.java:331)
[MOBIHELP]  at android.content.Context.getString(Context.java:358)
[MOBIHELP]  at com.freshdesk.mobihelp.e.v.c(Unknown Source)
[MOBIHELP]  at com.freshdesk.mobihelp.service.a.k.a(Unknown Source)
[MOBIHELP]  at com.freshdesk.mobihelp.service.MobihelpService.onHandleIntent(Unknown Source)
[MOBIHELP]  at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
[MOBIHELP]  at android.os.Handler.dispatchMessage(Handler.java:102)
[MOBIHELP]  at android.os.Looper.loop(Looper.java:136)
[MOBIHELP]  at android.os.HandlerThread.run(HandlerThread.java:61)

Can you help me with this?

Thanks

**Comment by idotene** [comment]
Hi,

Can you try adding to your resources folder the existing resources from
FreshDesk SDK?

Let me know if it fixed the bug.

**Comment by RasaCosmin** [comment]
Thanks for your fast reply.
I include all res folder from FreshDesk SDK but it doesn't fix the bug.

**Comment by idotene** [comment]
I'll try to take a look on this bug early next week.

**Comment by idotene** [comment]
I can't test this scenario since my company isn't using a conversation feature in FreshDesk.
I have rebuild the dll and I made sure that all the resources are built. can you check and verify that it works now?

**Comment by idotene** [comment]
Have you tested this fix?
